version: "3.4"

services:
  postgres:
    container_name: learning-sequilize-postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tast_management_db
volumes:
  postgres_data:
